services:
  mysql:
    image: mysql:8.0
    container_name: radar-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecureMilitaryPassword
      MYSQL_DATABASE: mysql_db
    volumes:
      - ./db/radar-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  dynamodb:
    image: amazon/dynamodb-local:3.1.0
    container_name: radar-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./db/radar-dynamodb:/data:rw
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
