services:
  mysql:
    image: mysql:8.0
    container_name: radar-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecureMilitaryPassword
      MYSQL_DATABASE: radar_db
    volumes:
      - ./db/radar-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  dynamodb:
    image: mongo:6.0
    container_name: radar-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecureMilitaryPassword
    volumes:
      - ./db/radar-mongodb/data:/data/db:rw
      - ./db/radar-mongodb/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')", "-u", "root", "-p", "SuperSecureMilitaryPassword", "--authenticationDatabase", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
